version: "3.8"

services:
  app:
    build: .
    container_name: rag_app
    ports:
      - "8000:8000"  # настройте порт при необходимости
    environment:
      - ENV=production
    volumes:
      - .:/app
